apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
spec:
  selector:
    matchLabels:
      app: employee-app
  replicas: 1
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          image: gcr.io/valid-heuristic-293706/demo-app:20201118
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 20
            httpGet:
              port: 8080
              path: /actuator/health/readiness